In [2]:
#Importing NumPy
import numpy as np

In [4]:
#Creating a 1-D list 
mylist = [1,2,3]

In [6]:
np.array(mylist)

array([1, 2, 3])

In [8]:
#Creating a nested list
nested_list = [[1,2],[3,4],[5,6]]

In [10]:
#Print the nested list
nested_list

[[1, 2], [3, 4], [5, 6]]

In [12]:
#Convert the nested list into a NumPy array
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
#Form a list with elements of a range
#np.arange(starting number, upto number)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#Form a list with elements of a range with step size
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
#Create a 1-D array of zeros
np.zeros(3)

array([0., 0., 0.])

In [29]:
#Create a 2-D array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#Create a 1-D array of ones
np.ones(3)

array([1., 1., 1.])

In [33]:
#Create a 2-D array of on#es
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#Create an array of evenly spaced numbers between the specified range - to get equally spaced points in a range
#np.linspace(starting number, upto number, no. of spaces )
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
#Generate random numbers between 0 and 1
np.random.rand(5)

array([0.9972226 , 0.80053844, 0.69061358, 0.60983453, 0.7304642 ])

In [42]:
#Generate a random integer in a range
#inclusive of lower bound only
np.random.randint(1,100) 

55

In [52]:
#Generate n-random integers in a range- inclusive of lower bound only
np.random.randint(1,100,20)

array([94, 45, 95, 90, 80, 36, 85, 60, 55, 89, 22, 51, 56, 43, 37, 92,  6,
       38, 20, 46])